# Header
menu:
  首页: /
  分类: /categories
  标签: /tags
  友链: /links
  留言: /messages
  关于: /about
logo: https://qiniu.miiiku.xyz/src/images/logo.png
banner: https://qiniu.miiiku.xyz/src/images/banner.jpg
# banner: css/images/banner.jpg

# large cover
# long: [article, link]
# short: [category, tag]
large_legnth:
  long: 20
  short: 5

# 一言
# docs: https://hitokoto.cn/api
# type: [a, b, c, d, e, f, g]
hitokoto:
  enable: true
  type: a

# valine 评论
# docs: https://valine.js.org
# You can get your appid and appkey from https://leancloud.cn
# 这里appId和appKey一定一定要改成自己的，没有的话去https://leancloud.cn这个网站注册创建一个
valine:
  enable: true
  appId: oTmfgIaoB7PfPATvA9tsOwTu-gzGzoHsz
  appKey: PPbJycuezKD3BJlhHUy8zOnG
  avatar: mm
  placeholder: 随便说点什么叭～
  notify: true
  visitor: true
  pageSize: 10

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# waterfall 瀑布流
# docs: https://github.com/miiiku/waterfall
# Specific configuration information go to `layout/plug-in/waterfall.ejs`
waterfall: true

# zoom 图片预览
# docs: https://github.com/miiiku/zoom
zoom:
  enable: true
  margin: 15
  padding: 15
  radius: 5
  specify:
  filter: "gallery" # filter Front-matter photos


# widget behavior
archive_type: 'monthly'
show_count: false

# beian
beian: 蜀ICP备15014309号

# Miscellaneous
google_analytics: 
gauges_analytics: 
baidu_analytics: 410f4beade12e8df64ea4c5622313220
tencent_analytics: 64852535
favicon: /favicon.ico

permalink: true